# Generated by Django 4.2.10 on 2024-02-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoCoder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
