# Generated by Django 4.2.10 on 2024-02-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoCoder', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='snippet',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.TextField(default='', max_length=400),
        ),
    ]
