# Generated by Django 4.2.10 on 2024-02-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoCoder', '0005_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='choice1',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='choice2',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='choice3',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='choice4',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='correctChoice',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
