# Generated by Django 4.2.10 on 2024-02-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoCoder', '0007_rename_text_questions_question_useranswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
